; // CONSTANTE

    ;  pour dsn  tel que $dsn =  "mysql:dbname=sdbm_v2;host=localhost:3306";
        NOMDB = "sdbm_v2"
        NOMHOST = "localhost"
        PORT = ":3306"
    ; // pour Connexion
        USERNAME = "root"
        PASSWORD = ""
    