; // CONSTANTE

    ;  pour dsn     // $dsn =  "mysql:dbname=sdbm_v2;host=localhost:3306";
        NOMDB = "sdbm_v2"
        NOMSERV = "localhost"
        PORT = ":3306"
    ; // pour Connexion
        USERNAME = "root"
        PASSWORD = ""
    